services:
  mysql:
    image: mysql:8.0.33
    restart: always
    container_name: mysql-1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${HANKKI_ROOT_PASSWORD}
      MYSQL_DATABASE: ${HANKKI_DATABASE}
      MYSQL_USER: ${HANKKI_USERNAME}
      MYSQL_PASSWORD: ${HANKKI_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-1
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      HANKKI_USERNAME: ${HANKKI_USERNAME}
      HANKKI_PASSWORD: ${HANKKI_PASSWORD}
      HANKKI_DATABASE: ${HANKKI_DATABASE}
      OPENAI_SECRET_KEY: ${OPENAI_SECRET_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
    networks:
      - app-network

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
    container_name: frontend-1
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
