spring:
  application:
    name: hankkiwiki

  datasource:
    url: jdbc:mysql://mysql:3306/${HANKKI_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${HANKKI_USERNAME}
    password: ${HANKKI_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.hankki.domain.diet.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.hankki: DEBUG
    org.mybatis: DEBUG
    jdbc.sqlonly: DEBUG
    org.springframework.context.annotation: DEBUG
    org.mybatis.spring.mapper: DEBUG

server:
  port: 8081