spring:
  application:
    name: hankkiwiki

  datasource:
    url: jdbc:mysql://localhost:3306/hankkiwiki?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  mybatis:
    mapper-locations: classpath:/mappers/**/*.xml
    type-aliases-package: com.hankki.domain
    configuration:
      map-underscore-to-camel-case: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
